window.width=800
window.height=600
window.name=2D Shooter
window.fullscreen=false
window.resizable=true

opengl.vsync=true
opengl.targetFPS=60

keybind.move_up=W
keybind.move_down=S
keybind.move_left=A
keybind.move_right=D
keybind.pause=ESCAPE
keybind.restart=R